Controllers/BowlingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using s1411038021_NetFinal.Models;
using s1411038021_NetFinal.ViewModels;
using s1411038021_NetFinal.Services;

namespace s1411038021_NetFinal.Controllers
{
    public class BowlingController : Controller
    {
        public readonly CarNewsDBService CarNewsService = new CarNewsDBService();
        public readonly ballBrandDBService ballService = new ballBrandDBService();
        public readonly CartDBService CartService = new CartDBService();
        // GET: Bowling
        public ActionResult Index()
        {
            CarNewsViewModels Data = new CarNewsViewModels();
            Data.CarList = CarNewsService.GetCarList();
            Data.NewsList = CarNewsService.GetNewsList();
            return View(Data);
        }
        public ActionResult Item(int bid,int brandid,int flareid)
        {
            ballBrandViewModels Data = new ballBrandViewModels();
            /*可以把場牌跟球皮強度都放在ball就好 GetBallById的SQL語法跟廠牌球皮強度JOIN 這樣就不用丟VIEWMODEL到VIEW*/
            Data.ball = ballService.GetBallByBid(bid);
            Data.Brand = ballService.GetBrandById(brandid);
            Data.Flare = ballService.GetFlareById(flareid);
            return View(Data);
        }
        public ActionResult CreateNews()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult CreateNews([Bind(Include = "ntitle")]News Data)
        {
            CarNewsService.InsertNews(Data);
            return RedirectToAction("Index");
        }
        public ActionResult EditNews(string nid)
        {
            News Data = CarNewsService.GetNewByid(nid);
            return View(Data);
        }
        [HttpPost]
        public ActionResult EditNews([Bind(Include = "nid,ntitle")] News Data)
        {
            CarNewsService.EditNew(Data);
            return RedirectToAction("Index");
        }
        public ActionResult CreateBall()
        {
            ballBrandViewModels Data = new ballBrandViewModels();
            Data.BrandList = ballService.GetBrandList();
            Data.FlareList = ballService.GetFlareList();
            return View(Data);
        }
        [HttpPost]
        public ActionResult Createball(int brandid, int flareid, HttpPostedFileBase files,[Bind(Include = "ball")]ballBrandViewModels UpdateData)
        {
            if (files == null) //如果沒圖片重新導回
            {
                TempData["message"] = "請上傳圖片";
                return RedirectToAction("Createball");
            }
            string serverPath = Server.MapPath("~/Images/ballimg/");
            files.SaveAs(serverPath + files.FileName);
            UpdateData.ball.bfile = files.FileName;
            UpdateData.ball.Brandid = brandid;
            UpdateData.ball.Flareid = flareid;
            ballService.CreateBall(UpdateData.ball);
            return RedirectToAction("product", new { Search = UpdateData.ball.bname });
            
        }
        public ActionResult Delete(int nid)
        {
            CarNewsService.DeleteNew(nid);
            return RedirectToAction("Index");
        }
        public ActionResult product(string Search,int Page = 1,int brandid = 0,int flareid = 0)
        {
            ballBrandViewModels Data = new ballBrandViewModels();
            Data.Paging = new ForPaging(Page);
            Data.Search = Search;
            Data = ballService.GetAllBall(brandid,flareid,Data.Paging,Data.Search);
            Data.BrandList = ballService.GetBrandList();
            Data.FlareList = ballService.GetFlareList();
            Data.Flareid = flareid;
            Data.Brandid = brandid;
            return View(Data);
        }
        public ActionResult Editball(int bid,int flareid,int brandid)
        {
            ballBrandViewModels Data = new ballBrandViewModels();
            Data.ball = ballService.GetBallByBid(bid);
            Data.Flareid = flareid;
            Data.Brandid = brandid;
            Data.BrandList = ballService.GetBrandList();
            Data.FlareList = ballService.GetFlareList();
            return View(Data);
        }
        [HttpPost]
        public ActionResult Editball(int bid,int Brandid,int Flareid,HttpPostedFileBase files, [Bind(Include = "ball")]ballBrandViewModels UpdateData)
        {
            UpdateData.ball.Brandid = Brandid;
            UpdateData.ball.Flareid = Flareid;
            UpdateData.ball.bid = bid;
            if(files != null)
            {
                string serverPath = Server.MapPath("~/Images/ballimg/");
                files.SaveAs(serverPath + files.FileName);
                UpdateData.ball.bfile = files.FileName;
            }
            ballService.UpdateBall(UpdateData.ball);
            return RedirectToAction("product", new {Search = UpdateData.ball.bname});
        }
        public ActionResult Deleteball(int bid)
        {
            ballService.Deleteball(bid);
            return RedirectToAction("product");
        }
        [HttpPost]
        public ActionResult CreateCart(int bid)
        {
            CartService.InsertCart(bid);
            return Json((new { message = "成功添加商品到購物車。" }));
        }
        public ActionResult UserEdit()
        {
            ballBrandViewModels Data = new ballBrandViewModels();
            Data.BrandList = ballService.GetBrandList();
            return View(Data);
        }
        public ActionResult CreateNewBrand()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult CreateNewBrand(Brand Data)
        {
            List<Brand> check = ballService.GetBrandList();
            foreach(var item in check)
            {
                if(item.Brandid == Data.Brandid || item.Brandname == Data.Brandname)
                {
                    TempData["message"] = "編號或名稱重複，請重新輸入";
                    return RedirectToAction("UserEdit");
                }
            }
            if(Data.Brandname == "" || Data.Brandid == 0)
            {
                TempData["message"] = "編號不可為0、名稱不可空白，請重新輸入";
                return RedirectToAction("UserEdit");
            }
            ballService.CreateBrand(Data);
            return RedirectToAction("UserEdit");
        }
        public ActionResult DeleteBrand(int Brandid)
        {
            ballService.DeleteBrand(Brandid);
            return RedirectToAction("UserEdit");
        }
        public ActionResult EditBrand(int Brandid)
        {
            Brand Data = ballService.GetBrandById(Brandid);
            return View(Data);
        }
        
        [HttpPost]
        public ActionResult EditBrand(Brand UpData)
        {
            ballService.UpdateBrand(UpData);
            return RedirectToAction("UserEdit");
        }
    }
}

Controllers/MyCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using s1411038021_NetFinal.Models;
using s1411038021_NetFinal.Services;
using s1411038021_NetFinal.ViewModels;

namespace s1411038021_NetFinal.Controllers
{
    public class MyCartController : Controller
    {
        CartDBService CartService = new CartDBService();
        // GET: MyCart
        public ActionResult Index()
        {
            CartViewModel DataList = new CartViewModel();
            DataList.CartList = CartService.GetAllCart();
            DataList.Sum = CartService.GetSum();
            return View(DataList);
        }
        public ActionResult Delete(int CartId)
        {
            CartService.Delete(CartId);
            return RedirectToAction("Index");
        }
        public ActionResult EditCart(int CartId)
        {
            Cart Data = CartService.GetCartByCartId(CartId);
            return PartialView(Data);
        }
        [HttpPost]
        public ActionResult EditCart(int CartId,[Bind(Include ="amount")]Cart UpdateData)
        {
            UpdateData.CartId = CartId;
            if(UpdateData.amount>0)
            {
                CartService.Updateamount(UpdateData);
            }
            else
            {
                TempData["message"] = "數量不可為0或少於0";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Views/MyCart/EditCart.cshtml
@model s1411038021_NetFinal.Models.Cart
<link href="~/Content/Item.css" rel="stylesheet" />

<div class="edit-content">
    @using (Html.BeginForm("EditCart", "MyCart",new {CartId = Model.CartId},FormMethod.Post))
    {
        <div class="item">
            <div class="item-img">
                <img src="@Url.Content("~/Images/ballimg/" + Html.DisplayFor(Model => Model.bfile))" alt="" id="ballimg" />
            </div>
            <div class="item-content">
                <h2>訂單資訊</h2>
                <table class="table">
                    <tr>
                        <td>@Html.DisplayNameFor(Model => Model.bname)</td>
                        <td>@Html.DisplayFor(modelItem => modelItem.bname)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.bprise)</td>
                        <td>@Html.DisplayFor(modelItem => modelItem.bprise)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.BrandName)</td>
                        <td>@Html.DisplayFor(modelItem => modelItem.BrandName)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.FlareLevel)</td>
                        <td>@Html.DisplayFor(modelItem => modelItem.FlareLevel)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.amount)</td>
                        <td class="black" style="font-size:18px;">
                            @Html.TextBoxFor(model => model.amount, new { type = "number" })
                            @Html.ValidationMessageFor(model => model.amount)
                        </td>
                    </tr>
                </table>
                <div class="work">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MyCart/Index.cshtml
@model s1411038021_NetFinal.ViewModels.CartViewModel
@if (TempData["message"] != null)
{
    <script type="text/javascript">
            var message = @Html.Raw(Json.Encode(TempData["message"]));
            alert(message);
    </script>
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}
<style>
    h3 {
        width: 100%;
        justify-content: flex-start;
        display: flex;
        color: white;
    }

    .total {
        font-size: 30px;
        font-weight: bolder;
        justify-content: end;
        position: fixed;
        right: 15%;
        bottom: 10%;
    }

    th, td {
        text-align: center;
    }

    .Cart {
        width: 100%;
        display: flex
    }

    .CartEmpty p {
        color: white;
        font-size: 16px;
        padding: 5px;
        text-align: center;
    }

    .CartEmpty a:visited, .CartEmpty a:link {
        background-color: white;
        padding: 5px 10px;
        border-radius: 5px;
        color: black;
        text-decoration: none;
    }

    .CartEmpty a:hover {
        background-color: orange;
        color: white;
    }

    .CartList {
        width: 45%;
    }

    #details-content {
        width: 60%;
        position: fixed;
        right: 0;
    }
    .footer{
        position:fixed;

    }
</style>
<h3>您的購物車</h3>

<div class="Cart">
    <div class="CartList">
        @if (!Model.CartList.Count.Equals(0))
        {
            foreach (var item in Model.CartList)
            {
                <div class="CartBox">
                    <div class="Cartimg">
                        <img src="@Url.Content("~/Images/ballimg/" + item.bfile)" alt="" />
                    </div>
                    <div class="Cart-content">
                        <ul>
                            <li>
                                <span>@Html.DisplayNameFor(model => model.CartList[0].bname)</span>
                                @Html.DisplayFor(modelItem => item.bname)
                            </li>
                            <li>
                                <span>@Html.DisplayNameFor(model => model.CartList[0].FlareLevel)</span>
                                @Html.DisplayFor(modelItem => item.FlareLevel)
                            </li>
                            <li>
                                <span>@Html.DisplayNameFor(model => model.CartList[0].BrandName)</span>
                                @Html.DisplayFor(modelItem => item.BrandName)
                            </li>
                            <li>
                                <span>@Html.DisplayNameFor(model => model.CartList[0].bprise)</span>
                                @Html.DisplayFor(modelItem => item.bprise)
                            </li>
                            <li>
                                <span>@Html.DisplayNameFor(model => model.CartList[0].amount)</span>
                                @Html.DisplayFor(modelItem => item.amount)
                            </li>
                        </ul>
                        <div class="Cart-btn">
                            <button class="Editbtn newbtn" data-id="@item.CartId">修改數量</button>
                            @Html.ActionLink("詳細資料", "Item", "Bowling", new { bid = item.bid, brandid = item.Brandid, flareid = item.Flareid }, new { @class = "newbtn" })
                            @Html.ActionLink("刪除", "Delete", new { CartId = item.CartId }, new { @class = "newbtn" })
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="CartEmpty">
                <p>您的購物車空空的，趕快去選購吧</p>
                <p>@Html.ActionLink("商品列表", "product", "Bowling")</p>
            </div>
        }
    </div>
    <div id="details-content">
        <div id="details">
        </div>
        <div class="total">總金額：@Html.DisplayFor(model => model.Sum)</div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MyCart/Index1.cshtml
@model IEnumerable<s1411038021_NetFinal.Models.Cart>

@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

<h2>Index1</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.bid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bprise)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bfile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlareLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrandName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.bid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bprise)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bfile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FlareLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrandName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CartId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CartId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CartId })
        </td>
    </tr>
}

</table>